#!/usr/bin/env bash
# customs nginx
# First install the Nginx server
sudo apt update
sudo apt-get install -y nginx 
echo "Hello World!" > index.html
sudo mv index.html /var/www/html
#
# Creates a custom 404.html file
echo "Ceci n'est pas une page" > /var/www/html/404.html
#
# Configuring the server to redirect the 404.html page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /404.html;
    location = /404.html{
        internal;
    }
}" > /etc/nginx/sites-available/default
#
# Restarting the nginx service
sudo service nginx restart
