#!/usr/bin/env bash
# configure nginx
sudo apt update
sudo apt-get -y install nginx
# sudo ufw allow "Nginx HTTP"
sudo service nginx start
sudo echo "Hello, World!" | sudo tee /var/www/html/index.html
#
# Write into a /etc/nginx/sites-available/default file
# The /etc/nginx/sites-available/default file in Nginx serves as the default config
sudo echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    add_header X-Served-By \$hostname;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    location / {
        try_files \$uri \$uri/ =404;
    }
}" | sudo tee  /etc/nginx/sites-available/default
#
# Restart the Nginx service
sudo service nginx restart
