#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an a
echo "Enter IP address '8.8.8.8': "
read -r ip_var
if [ ! "$ip_var" ] ; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
