#!/usr/bin/env bash
# Write a Bash script that displays:
#To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
var="To infinity and beyond"
var2="I am invincible!!!"
while [ "$var" ]; do
	echo "$var"
	sleep 2
	echo "$var2"
done
