#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
#+ displays good luck for the 8th loop iteration
#+ displays Best School for the other iteration
bst=0
while [ $bst -lt 9 ]; do
	echo "Best School"

	if [ $bst = 2 ]; then
		echo "bad luck"
	fi
	if [ $bst = 5 ]; then
		echo "good luck"
	fi
	((bst++))
done
