#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
#+ displays good luck for the 8th loop iteration
#+ displays Best School for the other iteration
bst=0
while [ $bst -lt 10 ]; do
	echo "Best School"
	((bst++))

	if [ $bst = 3 ]; then
		echo "bad luck"
	fi
	if [ $bst = 7 ]; then
		echo "good luck"
	fi
done
