#!/usr/bin/env bash
# displays 4 and then bad luck from china for the 4th loop operation
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
num=0
while [ $num -lt 20 ]; do
	case $num in
		'1')
		echo $num
		;;
esac
