#!/usr/bin/env bash
# displays 4 and then bad luck from china for the 4th loop operation
# displays 9 and then bad luck from Japan for the 9th loop iteration
# displays 17 and then bad luck from Italy for the 17th loop iteration
num=0
while [ $num -le 20 ]; do
	case $num in
		'1' | '2' | '3' | '5' | '6' | '7' | '8' | '10' | '11')
		echo $num
		;;
		'12' | '13' | '14' | '15' | '16' | '18' | '19' | '20')
		echo $num
		;;
		'4')
		echo -e "$num\nbad luck from china"
		;;
		'9')
		echo -e "$num\nbas luck from Japan"
		;;
		'17')
		echo -e "$num\nbad luck from Italy"
		;;
	esac
	((num++))
done
