#!/usr/bin/env bash
# displays the time for 12hours and 59 minutes
hour=0
min=0
while [ $hour -le 12 ]; do
	while [ $min -le 60 ];do
		if [ $min = 1 ]; then
			echo "Hour: $min"
		fi
		echo $min
	((min++))
	done
	if [ $hour = 0 ]; then
		echo "Hour: $hour"
	fi
	echo $hour
	((hour++))
done
