#!/usr/bin/env bash
# displays the time for 12hours and 59 minutes
hour=0
min=1
while [ $hour -le 12 ]; do
	if [ $hour = 1 ]; then
		echo "Hour: $hour"
	fi
	echo $hour
	((hour++))
	while [ $min -lt 60 ];do
		if [ $min = 0 ]; then
			echo "Hour: 0"
		fi
		echo $min
		((min++))
	done
done
