#!/usr/bin/env bash
# displays CWD in a list format
#where only the part of the name
for file in *; do
	if [[ ! "file" =~ ^\. ]]; then
		display_name=$(echo "file" | cut -d'-' -f2-)
		echo "- $display_name"
	fi
done
