#!/usr/bin/env bash
# gives information about the School file
var="school"
if [ -e $var ]; then
	echo "$var file exists"
	if [ -s "$var" ]; then
		echo "$var file is empty"
	fi
	else
		echo "$var file does not exist"
fi
