#!/usr/bin/env bash
# gives information about the School file
var="school"
if [ -e $var ]; then
	echo "$var file exists"
	elif [ -s $var ]; then
		echo "$var file is empty"
	else
		echo "$var file does not exist"
fi
